name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

env:
  PYTHON_VERSION: 3.8

jobs:
  tests:
    name: Tests & Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Uvicorn with FastAPI for Test Coverage
        run: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir ./src --log-level trace --no-access-log & sleep 5

      - name: Run Tests with pytest
        run: pytest

      - name: Generate Code Coverage Report
        run: coverage run -m pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
